Added basic roles function
Cubix651/expenses-splitter pull request #12
Opened 2020-12-13 18:56 UTC by Filcz9

Dodałem podstawowe funkcje roli w rozliczeniu. Kiedy dodany użytkownik wchodzi do rozliczenia którego nie stworzył nie może dodawać nowych użytkowników. Teraz będę to wszystko rozwijał, dodawał możliwość usuwania i edycji, no i przypisywanie do grup. A to można mergować.

2020-12-13 20:55 UTC, Cubix651 requested changes

2020-12-13 20:55 UTC, Cubix651 commented on ExpensesSplitter.Frontend/src/app/settlement-summary/settlement-summary.component.ts
> +  role: any;
Stwórz enum we frontendzie, który będzie odpowiadał różnym rolom.

2020-12-13 20:55 UTC, Cubix651 commented on ExpensesSplitter.WebApi/Database/Models/SettlementUser.cs
> +        public string RoleId { get; set; }
Konsekwentnie tutaj także lepiej, żeby rola była enumem.

2020-12-13 20:55 UTC, Cubix651 commented on ExpensesSplitter.WebApi/Controllers/SettlementsController.cs
> +                    RoleId = "2"
W backendzie też stwórz enum i jego używaj do ustawiania roli.

2020-12-14 15:50 UTC, Filcz9 commented
Dodałem enuma na backendzie, i jeszcze muszę go do końca na froncie ogarnąć, Dodałem opcję usuwania użytkowników i tworzenia grup. Jutro powinna wejść edycja użytkowników

2020-12-14 16:59 UTC, Cubix651 reviewed
Super, dzięki za zmiany. Fajnie, że też usunąłeś trochę tych zbędnych komentarzy. Dodałem jeszcze kilka uwag.

2020-12-14 16:59 UTC, Cubix651 commented on ExpensesSplitter.Frontend/src/app/settlement-summary/settlement-summary.component.ts
> +enum role {
Wydziel to osobnego pliku i nazwij z wielkiej litery.

2020-12-14 16:59 UTC, Cubix651 commented on ExpensesSplitter.Frontend/src/app/settlement-summary/settlement-summary.component.ts
> +  userRole:{
Mapowanie też przenieś do innego pliku, jeśli rzeczywiście jest potrzebne.

2020-12-14 16:59 UTC, Cubix651 commented on ExpensesSplitter.Frontend/src/app/settlement-summary/settlement-summary.component.ts
> +      console.log
Tutaj chyba coś zostało co nie powinno.

2020-12-14 16:59 UTC, Cubix651 commented on ExpensesSplitter.WebApi/Database/Models/SettlementUser.cs
> +        public enum Role { Admin, Watcher, Editor }
Przenieś enum do osobnego pliku także w backendzie.

2020-12-28 11:46 UTC, merged